---
name: Python package

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4

      - name: Set up Python ${{ matrix.python-version }}
        # yamllint disable-line rule:comments
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Test with pytest
        run: |
          pip install -e ".[test]"
          pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest test results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3  # v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint with Flake8
    steps:
      - name: Check out source repository
        # yamllint disable-line rule:comments
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Set up Python environment
        # yamllint disable-line rule:comments
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba  # v2

  ruff-lint:
    runs-on: ubuntu-latest
    name: Lint with Ruff
    steps:
      - name: Check out source repository
        # yamllint disable-line rule:comments
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Set up Python environment
        # yamllint disable-line rule:comments
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.11"

      - name: Ruff Lint
        run: |
          pip install -e ".[pipeline]"

          # default set of ruff rules with GitHub Annotations
          ruff --output-format=github --target-version=py310 src/
