---
name: Create a release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        # yamllint disable-line rule:comments
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        with:
          # to create protected tags
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          release-type: python
          signoff: "Matthias Kay <matthias.kay@hlag.com>"
