---
name: Execute ChatOps command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - help-command

jobs:
  help-command:
    name: "ChatOps: /help"
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:comments
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Choose maintainer
        id: vars
        run: |
          maintainer=$(grep -oE "@[a-zA-Z0-9_-]+" CODEOWNERS | shuf -n 1)
          echo "maintainer=$maintainer" >> "$GITHUB_OUTPUT"

      - name: Create comment
        # yamllint disable-line rule:comments
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
        with:
          # yamllint disable rule:line-length
          script: |
            // adds a comment to the PR (there is the issue API, which works work PRs too)
            github.rest.issues.createComment({
              issue_number: context.payload.client_payload.github.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey there ${{ steps.vars.outputs.maintainer }}, could you please help @${{ github.event.client_payload.github.payload.comment.user.login }} out?'
            })
          # yamllint enable rule:line-length
