---
name: PR commented

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types:
      - created

jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        # yamllint disable-line rule:comments
        uses: peter-evans/slash-command-dispatch@f996d7b7aae9059759ac55e978cff76d91853301 # v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          reactions: true
          commands: |
            help
