---
name: 'Check spelling'

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:comments
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # yamllint disable-line rule:comments
      - uses: streetsidesoftware/cspell-action@52cba17693dc12d7d8f521631037008a17c93e53 # v5.0.0
        with:
          config: .cspell.json
