---
name: 'Check spelling'

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:comments
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # yamllint disable-line rule:comments
      - uses: streetsidesoftware/cspell-action@c8855adc59d29c3fc73b5453b16717947c3f050c # v2.26.3
        with:
          config: .cspell.json
